# 尝试
name: douban
on:
  schedule:
  - cron: "* 0 * * *"
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: delete old file
      run: |
        rm -rf ./data
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: senup
        type: movie
        format: csv
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: senup
        type: book
        format: csv
        dir: ./data/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: '豆瓣电影和书籍已更新'
        add: './data/douban'
